# Book settings
title:
author: Development Data Partnership
logo: docs/images/logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

#######################################################################################
# Execution settings
execute:
    execute_notebooks: force
    allow_errors: true
    exclude_patterns:
        - notebooks/*.ipynb

only_build_toc_files: true

#######################################################################################
# HTML-specific settings
html:
    favicon: images/favicon.ico
    home_page_in_navbar: false
    use_repository_button: true
    use_issues_button: true
    #extra_navbar: "By Development Data Partnership"
    baseurl: https://datapartnership.org/

#######################################################################################
# Launch button settings
repository:
    url: https://github.com/datapartnership/docs
